# This is the network config written by 'subiquity'
# NOTE: configuration requires static IP assignment on DHCP server
network:
  version: 2
  wifis:
    # note - check this interface
    wlp6s0:
      access-points:
        WabbitSeason:
          password: password_goes_here
          dhcp4: true
