---
# tasks file for myuser

- name: Perform apt cache update
  ansible.builtin.apt:
    update_cache: yes
  ignore_errors: true

- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: present
  ignore_errors: true

- name: Install standard packages
  ansible.builtin.apt:
    pkg:
    - emacs-nox
    - net-tools
    - htop
    - git
    - ansible
    - yamllint

- name: Check if lxc* packages are installed
  shell: apt list --installed | grep "*lxc*"
  ignore_errors: true
  changed_when: no
  no_log: True
  register: lxc_packages

- name: Remove LXC packages
  apt:
    name: "*lxc*"
    state: absent
    autoremove: yes
  when: lxc_packages.rc == 0

- name: Check if lxd* packages are installed
  shell: apt list --installed | grep "*lxd*"
  ignore_errors: true
  changed_when: no
  no_log: True
  register: lxd_packages

- name: Remove LXD packages
  apt:
    name: "*lxd*"
    state: absent
    autoremove: yes
  when: lxd_packages.rc == 0

- name: Check if lxd snap is installed
  shell: snap list lxd
  ignore_errors: true
  changed_when: no
  no_log: True
  register: lxd_snap

- name: Remove LXD snap
  command: snap remove lxd
  when: lxd_snap.rc == 0

- name: Install LXD snap
  command: snap install lxd
  when: install_lxd is defined and install_lxd == '1'

- name: Configure LXD
  command: lxd init --preseed /tmp/homelab-maas/lxc/lxd_hoard_preseed.yaml
  when: install_lxd is defined and install_lxd == '1'

- name: Check LXD install status
  shell: lxc network show lxdbr0
  ignore_errors: true
  changed_when: no
  no_log: True
  register: lxd_net_ok
  when: install_lxd is defined and install_lxd == '1'

- name: Configure LXD Bridge Network
  command: lxc network set lxdbr0 dns.mode=none && lxc network set lxdbr0 ipv4.dhcp=false && lxc network set lxdbr0 ipv6.dhcp=false
  when: install_lxd is defined and install_lxd == '1' and lxd_net_ok == 0

- name: (ceph) install ceph prerequisites
  ansible.builtin.apt:
    pkg:
    - podman
    - cephadm

